name: Docker Build and Push

on:
  push:
    #   branches:
    #     - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: python-test

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # パッケージの書き込み権限を付与
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
