name: Docker Build and Push

on:
  push:
    #   branches:
    #     - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: python-test

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Container
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} 

    #   run: |
    #     docker build --tag ghcr.io/$GITHUB_ACTOR/pnovel:latest \
    #     --tag ghcr.io/$GITHUB_ACTOR/pnovel:$(echo $GITHUB_SHA | head -c7) \
    #    .


    # - name: Push Docker Image
    #   run: |
    #     docker push ghcr.io/$GITHUB_ACTOR/pnovel:latest
    #     docker push ghcr.io/$GITHUB_ACTOR/pnovel:$(echo $GITHUB_SHA | head -c7)